sudo: required

env:
- GHCVER=7.6.3
- GHCVER=7.8.4
- GHCVER=7.10.3
- GHCVER=8.0.2
- GHCVER=8.2.2
- GHCVER=8.4.3
- GHCVER=head

script:
- curl -sL https://raw.github.com/tomjaguarpaw/neil/930a726f/travis.sh | sh -s tomjaguarpaw 930a726f
